version: "3"

networks:
    pib-network:
        driver: bridge

services:
    angular-app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NODE_ENV: production # or 'development' for dev build
        ports:
            - "80:80"
        networks:
            - pib-network
        restart: always
