version: '3'

networks:
  pib-network:
    driver: bridge

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production  # or 'development' for dev build
    environment:
      - FLASK_API_BASE_URL=http://flask-app:5000
    ports:
      - "8080:80"
    networks:
      - pib-network
