export enum UrlConstants {
    PERSONALITY = "/voice-assistant/personality",
    CHAT = "/voice-assistant/chat",
    MOTOR = "/motor",
    CAMERA = "/camera-settings",
    PROGRAM = "/program",
    CODE = "code",
    ASSISTANT_MODEL = "/assistant-model",
    POSE = "/pose",
    BRICKLET = "/bricklet",
    HOST_IP = "/host-ip",
    RGB_BUTTON = "/button-programs",
    DIAGNOSTICS = "/diagnostics",
    DOCKER = "/docker",
    SYSTEM_REVISION = "/system/revision",
    SYSTEM_UPDATE = "/system/update",
    SYSTEM_UPDATE_STATUS = "/system/update/status",
    SYSTEM_UPDATE_LOG = "/system/update/log",
    SYSTEM_UPDATE_CANCEL = "/system/update/cancel",
    SYSTEM_UPDATE_CHECK = "/system/update/check",
    SYSTEM_UPDATE_AVAILABLE = "/system/update/available",
    MICROPHONE_ARRAY = "/system/microphone-array",
    HARDWARE_CONFIG = "/system/hardware-config",
    HARDWARE_VARIANT = "/system/hardware-variant",
    HARDWARE_CAPABILITIES = "/system/hardware-capabilities",
    CONTROLLER = "/controller",
    MARIMO = "/marimo",
}
