export enum UrlConstants {
    PERSONALITY = "/voice-assistant/personality",
    CHAT = "/voice-assistant/chat",
    MOTOR = "/motor",
    CAMERA = "/camera-settings",
    PROGRAM = "/program",
    CODE = "code",
    ASSISTANT_MODEL = "/assistant-model",
    POSE = "/pose",
    BRICKLET = "/bricklet",
    HOST_IP = "/host-ip",
    RGB_BUTTON = "/button-programs",
    DIAGNOSTICS = "/diagnostics",
    DOCKER = "/docker",
    MICROPHONE_ARRAY = "/system/microphone-array",
    HARDWARE_CONFIG = "/system/hardware-config",
    MARIMO = "/marimo",
}
