export enum UrlConstants {
    PERSONALITY = "/voice-assistant/personality",
    CHAT = "/voice-assistant/chat",
    MOTOR = "/motor",
    CAMERA = "/camera-settings",
    PROGRAM = "/program",
    CODE = "code",
    ASSISTANT_MODEL = "/assistant-model",
    POSE = "/pose",
    BRICKLET = "/bricklet",
    HOST_IP = "/host-ip",
    RGB_BUTTON = "/button-programs",
    SYSTEM_INFO = "/system/info",
    SYSTEM_CONTAINERS = "/system/containers",
    SYSTEM_BRICKLETS_STATUS = "/system/bricklets/status",
    SYSTEM_DIAGNOSTICS = "/system/diagnostics.zip",
}
