#!/usr/bin/env python3
"""Regenerate facemesh-topology.ts from MediaPipe's canonical tessellation."""

import ast
from pathlib import Path
from urllib.request import urlopen

SOURCE_URL = (
    "https://raw.githubusercontent.com/google-ai-edge/mediapipe/master/"
    "mediapipe/python/solutions/face_mesh_connections.py"
)
OUTPUT = Path(__file__).with_name("facemesh-topology.ts")


def tessellation_pairs(source):
    module = ast.parse(source)
    for node in module.body:
        if not isinstance(node, ast.Assign):
            continue
        if not any(
            isinstance(target, ast.Name)
            and target.id == "FACEMESH_TESSELATION"
            for target in node.targets
        ):
            continue
        return ast.literal_eval(node.value.args[0])
    raise ValueError("FACEMESH_TESSELATION was not found")


def unique_edges(pairs):
    edges = []
    seen = set()
    for first, second in pairs:
        edge = tuple(sorted((first, second)))
        if edge in seen:
            continue
        seen.add(edge)
        edges.append(edge)
    return edges


def main():
    source = urlopen(SOURCE_URL).read().decode("utf-8")
    pairs = tessellation_pairs(source)
    edges = unique_edges(pairs)
    assert len(pairs) == 2556
    assert len(edges) == 1322
    assert max(max(edge) for edge in edges) == 467

    lines = [
        "/**",
        " * Generated by generate-facemesh-topology.py from MediaPipe",
        " * FACEMESH_TESSELATION. Its 2556 triangle edges are deduplicated",
        " * as undirected edges here so interior mesh lines render once.",
        " */",
        "export const FACEMESH_INDEX_PAIRS: "
        "ReadonlyArray<readonly [number, number]> = [",
    ]
    lines.extend(f"    [{first}, {second}]," for first, second in edges)
    lines.append("];")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"source_pairs={len(pairs)} unique_edges={len(edges)} "
        f"max_index={max(max(edge) for edge in edges)}"
    )


if __name__ == "__main__":
    main()
