export interface MotorConfiguration {
    motorName: string;
    motorPathName: string;
    title: string;
    sliderIconLeft: string;
    sliderIconRight: string;
    captionLeft: string;
    captionRight: string;
}

export enum MotorPathName {
    TILT_FORWARD = "tilt-forward",
    TURN_HEAD = "turn-head",
    THUMB_RIGHT_STRETCH = "thumb-right-stretch",
    THUMB_RIGHT_OPPOSITION = "thumb-right-opposition",
    INDEX_RIGHT_STRETCH = "index-right-stretch",
    MIDDLE_RIGHT_STRETCH = "middle-right-stretch",
    RING_RIGHT_STRECTH = "ring-right-stretch",
    PINKY_RIGHT_STRECTH = "pinky-right-stretch",
    THUMB_LEFT_STRETCH = "thumb-left-stretch",
    THUMB_LEFT_OPPOSITION = "thumb-left-opposition",
    INDEX_LEFT_STRETCH = "index-left-stretch",
    MIDDLE_LEFT_STRETCH = "middle-left-stretch",
    RING_LEFT_STRECTH = "ring-left-stretch",
    PINKY_LEFT_STRECTH = "pinky-left-stretch",
    SHOULDER_HORIZONTAL_RIGHT = "shoulder-horizontal-right",
    SHOULDER_VERTICAL_RIGHT = "shoulder-vertical-right",
    UPPER_ARM_RIGHT_ROTATION = "upper-arm-right-rotation",
    ELBOW_RIGHT = "elbow-right",
    LOWER_ARM_RIGHT_ROTATION = "lower-arm-right-rotation",
    WRIST_RIGHT = "wrist-right",
    SHOULDER_HORIZONTAL_LEFT = "shoulder-horizontal-left",
    SHOULDER_VERTICAL_LEFT = "shoulder-vertical-left",
    UPPER_ARM_LEFT_ROTATION = "upper-arm-left-rotation",
    ELBOW_LEFT = "elbow-left",
    LOWER_ARM_LEFT_ROTATION = "lower-arm-left-rotation",
    WRIST_LEFT = "wrist-left",
}

export const motors: MotorConfiguration[] = [
    {
        motorName: "tilt_forward_motor",
        motorPathName: MotorPathName.TILT_FORWARD,
        title: "Tilt Forward",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "turn_head_motor",
        motorPathName: MotorPathName.TURN_HEAD,
        title: "Head Rotation",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "thumb_right_stretch",
        motorPathName: MotorPathName.THUMB_RIGHT_STRETCH,
        title: "Thumb",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "thumb_right_opposition",
        motorPathName: MotorPathName.THUMB_RIGHT_OPPOSITION,
        title: "Thumb Opposition",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "index_right_stretch",
        motorPathName: MotorPathName.INDEX_RIGHT_STRETCH,
        title: "Index Finger",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "middle_right_stretch",
        motorPathName: MotorPathName.MIDDLE_RIGHT_STRETCH,
        title: "Middle Finger",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "ring_right_stretch",
        motorPathName: MotorPathName.RING_RIGHT_STRECTH,
        title: "Ring Finger",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "pinky_right_stretch",
        motorPathName: MotorPathName.PINKY_RIGHT_STRECTH,
        title: "Pinky",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "thumb_left_stretch",
        motorPathName: MotorPathName.THUMB_LEFT_STRETCH,
        title: "Thumb",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "thumb_left_opposition",
        motorPathName: MotorPathName.THUMB_LEFT_OPPOSITION,
        title: "Thumb Opposition",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "index_left_stretch",
        motorPathName: MotorPathName.INDEX_LEFT_STRETCH,
        title: "Index Finger",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "middle_left_stretch",
        motorPathName: MotorPathName.MIDDLE_LEFT_STRETCH,
        title: "Middle Finger",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "ring_left_stretch",
        motorPathName: MotorPathName.RING_LEFT_STRECTH,
        title: "Ring Finger",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "pinky_left_stretch",
        motorPathName: MotorPathName.PINKY_LEFT_STRECTH,
        title: "Pinky",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "shoulder_horizontal_left",
        motorPathName: MotorPathName.SHOULDER_HORIZONTAL_LEFT,
        title: "Shoulder Horizontal",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "shoulder_vertical_left",
        motorPathName: MotorPathName.SHOULDER_VERTICAL_LEFT,
        title: "Shoulder Vertical",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "upper_arm_left_rotation",
        motorPathName: MotorPathName.UPPER_ARM_LEFT_ROTATION,
        title: "Upper Arm Rotation",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "elbow_left",
        motorPathName: MotorPathName.ELBOW_LEFT,
        title: "Elbow Position",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "lower_arm_left_rotation",
        motorPathName: MotorPathName.LOWER_ARM_LEFT_ROTATION,
        title: "Lower Arm Rotation",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "wrist_left",
        motorPathName: MotorPathName.WRIST_LEFT,
        title: "Wrist Position",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "shoulder_horizontal_right",
        motorPathName: MotorPathName.SHOULDER_HORIZONTAL_RIGHT,
        title: "Shoulder Horizontal",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "shoulder_vertical_right",
        motorPathName: MotorPathName.SHOULDER_VERTICAL_RIGHT,
        title: "Shoulder Vertical",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "upper_arm_right_rotation",
        motorPathName: MotorPathName.UPPER_ARM_RIGHT_ROTATION,
        title: "Upper Arm Rotation",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "elbow_right",
        motorPathName: MotorPathName.ELBOW_RIGHT,
        title: "Elbow Position",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "lower_arm_right_rotation",
        motorPathName: MotorPathName.LOWER_ARM_RIGHT_ROTATION,
        title: "Lower Arm Rotation",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
    {
        motorName: "wrist_right",
        motorPathName: MotorPathName.WRIST_RIGHT,
        title: "Wrist Position",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
    },
];

export const motorNameToConfiguration: Map<string, MotorConfiguration> =
    new Map();
for (const motor of motors) {
    motorNameToConfiguration.set(motor.motorPathName, motor);
}
