export interface MotorConfiguration {
    motorName: string;
    motorPathName: string;
    label: string;
    sliderIconLeft: string;
    sliderIconRight: string;
    captionLeft: string;
    captionRight: string;
    touchPointCenterX: number;
    touchPointCenterY: number;
    displaySettings: boolean;
    sourceMotorName: string;
}

export enum MotorPathName {
    TILT_FORWARD = "tilt-forward",
    TURN_HEAD = "turn-head",
    THUMB_RIGHT_STRETCH = "thumb-right-stretch",
    THUMB_RIGHT_OPPOSITION = "thumb-right-opposition",
    INDEX_RIGHT_STRETCH = "index-right-stretch",
    MIDDLE_RIGHT_STRETCH = "middle-right-stretch",
    RING_RIGHT_STRECTH = "ring-right-stretch",
    PINKY_RIGHT_STRECTH = "pinky-right-stretch",
    ALL_FINGERS_RIGHT = "all-fingers-right",
    THUMB_LEFT_STRETCH = "thumb-left-stretch",
    THUMB_LEFT_OPPOSITION = "thumb-left-opposition",
    INDEX_LEFT_STRETCH = "index-left-stretch",
    MIDDLE_LEFT_STRETCH = "middle-left-stretch",
    RING_LEFT_STRECTH = "ring-left-stretch",
    PINKY_LEFT_STRECTH = "pinky-left-stretch",
    ALL_FINGERS_LEFT = "all-fingers-left",
    SHOULDER_HORIZONTAL_RIGHT = "shoulder-horizontal-right",
    SHOULDER_VERTICAL_RIGHT = "shoulder-vertical-right",
    UPPER_ARM_RIGHT_ROTATION = "upper-arm-right-rotation",
    ELBOW_RIGHT = "elbow-right",
    LOWER_ARM_RIGHT_ROTATION = "lower-arm-right-rotation",
    WRIST_RIGHT = "wrist-right",
    SHOULDER_HORIZONTAL_LEFT = "shoulder-horizontal-left",
    SHOULDER_VERTICAL_LEFT = "shoulder-vertical-left",
    UPPER_ARM_LEFT_ROTATION = "upper-arm-left-rotation",
    ELBOW_LEFT = "elbow-left",
    LOWER_ARM_LEFT_ROTATION = "lower-arm-left-rotation",
    WRIST_LEFT = "wrist-left",
}

export const motors: MotorConfiguration[] = [
    {
        motorName: "tilt_forward_motor",
        motorPathName: MotorPathName.TILT_FORWARD,
        label: "Tilt Forward",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.5739329268292683,
        touchPointCenterY: 0.588793103448279,
        displaySettings: true,
        sourceMotorName: "tilt_forward_motor",
    },
    {
        motorName: "turn_head_motor",
        motorPathName: MotorPathName.TURN_HEAD,
        label: "Head Rotation",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.5884146341463414,
        touchPointCenterY: 0.6836206896551724,
        displaySettings: true,
        sourceMotorName: "turn_head_motor",
    },
    {
        motorName: "thumb_right_stretch",
        motorPathName: MotorPathName.THUMB_RIGHT_STRETCH,
        label: "Thumb",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.6051829268292683,
        touchPointCenterY: 0.1413793103448276,
        displaySettings: true,
        sourceMotorName: "thumb_right_stretch",
    },
    {
        motorName: "thumb_right_opposition",
        motorPathName: MotorPathName.THUMB_RIGHT_OPPOSITION,
        label: "Thumb Opposition",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.8048780487804879,
        touchPointCenterY: 0.3931034482758621,
        displaySettings: true,
        sourceMotorName: "thumb_right_opposition",
    },
    {
        motorName: "index_right_stretch",
        motorPathName: MotorPathName.INDEX_RIGHT_STRETCH,
        label: "Index Finger",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.2423780487804878,
        touchPointCenterY: 0.3482758620689655,
        displaySettings: true,
        sourceMotorName: "index_right_stretch",
    },
    {
        motorName: "middle_right_stretch",
        motorPathName: MotorPathName.MIDDLE_RIGHT_STRETCH,
        label: "Middle Finger",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.20198170731707318,
        touchPointCenterY: 0.531896551724138,
        displaySettings: true,
        sourceMotorName: "middle_right_stretch",
    },
    {
        motorName: "ring_right_stretch",
        motorPathName: MotorPathName.RING_RIGHT_STRECTH,
        label: "Ring Finger",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.2530487804878049,
        touchPointCenterY: 0.6629310344827586,
        displaySettings: true,
        sourceMotorName: "ring_right_stretch",
    },
    {
        motorName: "pinky_right_stretch",
        motorPathName: MotorPathName.PINKY_RIGHT_STRECTH,
        label: "Pinky",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.32698170731707316,
        touchPointCenterY: 0.7931034482758621,
        displaySettings: true,
        sourceMotorName: "pinky_right_stretch",
    },
    {
        motorName: "all_fingers_right",
        motorPathName: MotorPathName.ALL_FINGERS_RIGHT,
        label: "All Fingers",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.7545731707317073,
        touchPointCenterY: 0.5551724137931034,
        displaySettings: false,
        sourceMotorName: "index_right_stretch",
    },
    {
        motorName: "thumb_left_stretch",
        motorPathName: MotorPathName.THUMB_LEFT_STRETCH,
        label: "Thumb",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.3978658536585366,
        touchPointCenterY: 0.13793103448275862,
        displaySettings: true,
        sourceMotorName: "thumb_left_stretch",
    },
    {
        motorName: "thumb_left_opposition",
        motorPathName: MotorPathName.THUMB_LEFT_OPPOSITION,
        label: "Thumb Opposition",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.19588414634146342,
        touchPointCenterY: 0.3905172413793103,
        displaySettings: true,
        sourceMotorName: "thumb_left_opposition",
    },
    {
        motorName: "index_left_stretch",
        motorPathName: MotorPathName.INDEX_LEFT_STRETCH,
        label: "Index Finger",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.756859756097561,
        touchPointCenterY: 0.3456896551724138,
        displaySettings: true,
        sourceMotorName: "index_left_stretch",
    },
    {
        motorName: "middle_left_stretch",
        motorPathName: MotorPathName.MIDDLE_LEFT_STRETCH,
        label: "Middle Finger",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.8224085365853658,
        touchPointCenterY: 0.5293103448275862,
        displaySettings: true,
        sourceMotorName: "middle_left_stretch",
    },
    {
        motorName: "ring_left_stretch",
        motorPathName: MotorPathName.RING_LEFT_STRECTH,
        label: "Ring Finger",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.7842987804878049,
        touchPointCenterY: 0.6603448275862069,
        displaySettings: true,
        sourceMotorName: "ring_left_stretch",
    },
    {
        motorName: "pinky_left_stretch",
        motorPathName: MotorPathName.PINKY_LEFT_STRECTH,
        label: "Open/Close all fingers",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.6875,
        touchPointCenterY: 0.7896551724137931,
        displaySettings: true,
        sourceMotorName: "tilt_forward_motor",
    },
    {
        motorName: "all_fingers_left",
        motorPathName: MotorPathName.ALL_FINGERS_LEFT,
        label: "All Fingers",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.2454268292682927,
        touchPointCenterY: 0.5551724137931034,
        displaySettings: false,
        sourceMotorName: "index_left_stretch",
    },
    {
        motorName: "shoulder_horizontal_left",
        motorPathName: MotorPathName.SHOULDER_HORIZONTAL_LEFT,
        label: "Shoulder Horizontal",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.12195121951219512,
        touchPointCenterY: 0.15948275862068967,
        displaySettings: true,
        sourceMotorName: "shoulder_horizontal_left",
    },
    {
        motorName: "shoulder_vertical_left",
        motorPathName: MotorPathName.SHOULDER_VERTICAL_LEFT,
        label: "Shoulder Vertical",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.19207317073170732,
        touchPointCenterY: 0.20775862068965517,
        displaySettings: true,
        sourceMotorName: "shoulder_vertical_left",
    },
    {
        motorName: "upper_arm_left_rotation",
        motorPathName: MotorPathName.UPPER_ARM_LEFT_ROTATION,
        label: "Upper Arm Rotation",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.22560975609756098,
        touchPointCenterY: 0.4224137931034483,
        displaySettings: true,
        sourceMotorName: "upper_arm_left_rotation",
    },
    {
        motorName: "elbow_left",
        motorPathName: MotorPathName.ELBOW_LEFT,
        label: "Elbow Position",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.19969512195121952,
        touchPointCenterY: 0.5551724137931034,
        displaySettings: true,
        sourceMotorName: "elbow_left",
    },
    {
        motorName: "lower_arm_left_rotation",
        motorPathName: MotorPathName.LOWER_ARM_LEFT_ROTATION,
        label: "Lower Arm Rotation",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.3048780487804878,
        touchPointCenterY: 0.6387931034482759,
        displaySettings: true,
        sourceMotorName: "lower_arm_left_rotation",
    },
    {
        motorName: "wrist_left",
        motorPathName: MotorPathName.WRIST_LEFT,
        label: "Wrist Position",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.3780487804878049,
        touchPointCenterY: 0.8181034482758621,
        displaySettings: true,
        sourceMotorName: "wrist_left",
    },
    {
        motorName: "shoulder_horizontal_right",
        motorPathName: MotorPathName.SHOULDER_HORIZONTAL_RIGHT,
        label: "Shoulder Horizontal",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.8917682926829268,
        touchPointCenterY: 0.15948275862068967,
        displaySettings: true,
        sourceMotorName: "shoulder_horizontal_right",
    },
    {
        motorName: "shoulder_vertical_right",
        motorPathName: MotorPathName.SHOULDER_VERTICAL_RIGHT,
        label: "Shoulder Vertical",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.8079268292682927,
        touchPointCenterY: 0.20775862068965517,
        displaySettings: true,
        sourceMotorName: "shoulder_vertical_right",
    },
    {
        motorName: "upper_arm_right_rotation",
        motorPathName: MotorPathName.UPPER_ARM_RIGHT_ROTATION,
        label: "Upper Arm Rotation",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.7515243902439024,
        touchPointCenterY: 0.4224137931034483,
        displaySettings: true,
        sourceMotorName: "upper_arm_right_rotation",
    },
    {
        motorName: "elbow_right",
        motorPathName: MotorPathName.ELBOW_RIGHT,
        label: "Elbow Position",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.7530487804878049,
        touchPointCenterY: 0.5551724137931034,
        displaySettings: true,
        sourceMotorName: "elbow_right",
    },
    {
        motorName: "lower_arm_right_rotation",
        motorPathName: MotorPathName.LOWER_ARM_RIGHT_ROTATION,
        label: "Lower Arm Rotation",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.676829268292683,
        touchPointCenterY: 0.6586206896551724,
        displaySettings: true,
        sourceMotorName: "lower_arm_right_rotation",
    },
    {
        motorName: "wrist_right",
        motorPathName: MotorPathName.WRIST_RIGHT,
        label: "Wrist Position",
        sliderIconLeft: "/joint-control/slider-icons/hand-closed.svg",
        sliderIconRight: "/joint-control/slider-icons/hand-open.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.6577743902439024,
        touchPointCenterY: 0.8181034482758621,
        displaySettings: true,
        sourceMotorName: "wrist_right",
    },
];

export const motorPathNameToConfig: Map<string, MotorConfiguration> = new Map();
for (const motor of motors) {
    motorPathNameToConfig.set(motor.motorPathName, motor);
}
