export interface MotorConfiguration {
    motorName: string;
    motorPathName: string;
    title: string;
    sliderIconLeft: string;
    sliderIconRight: string;
    captionLeft: string;
    captionRight: string;
    touchPointCenterX: number;
    touchPointCenterY: number;
}

export enum MotorPathName {
    TILT_FORWARD = "tilt-forward",
    TURN_HEAD = "turn-head",
    THUMB_RIGHT_STRETCH = "thumb-right-stretch",
    THUMB_RIGHT_OPPOSITION = "thumb-right-opposition",
    INDEX_RIGHT_STRETCH = "index-right-stretch",
    MIDDLE_RIGHT_STRETCH = "middle-right-stretch",
    RING_RIGHT_STRECTH = "ring-right-stretch",
    PINKY_RIGHT_STRECTH = "pinky-right-stretch",
    THUMB_LEFT_STRETCH = "thumb-left-stretch",
    THUMB_LEFT_OPPOSITION = "thumb-left-opposition",
    INDEX_LEFT_STRETCH = "index-left-stretch",
    MIDDLE_LEFT_STRETCH = "middle-left-stretch",
    RING_LEFT_STRECTH = "ring-left-stretch",
    PINKY_LEFT_STRECTH = "pinky-left-stretch",
    SHOULDER_HORIZONTAL_RIGHT = "shoulder-horizontal-right",
    SHOULDER_VERTICAL_RIGHT = "shoulder-vertical-right",
    UPPER_ARM_RIGHT_ROTATION = "upper-arm-right-rotation",
    ELBOW_RIGHT = "elbow-right",
    LOWER_ARM_RIGHT_ROTATION = "lower-arm-right-rotation",
    WRIST_RIGHT = "wrist-right",
    SHOULDER_HORIZONTAL_LEFT = "shoulder-horizontal-left",
    SHOULDER_VERTICAL_LEFT = "shoulder-vertical-left",
    UPPER_ARM_LEFT_ROTATION = "upper-arm-left-rotation",
    ELBOW_LEFT = "elbow-left",
    LOWER_ARM_LEFT_ROTATION = "lower-arm-left-rotation",
    WRIST_LEFT = "wrist-left",
}

export const motors: MotorConfiguration[] = [
    {
        motorName: "tilt_forward_motor",
        motorPathName: MotorPathName.TILT_FORWARD,
        title: "Tilt Forward",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.5739329268292683,
        touchPointCenterY: 0.5887931034482759,
    },
    {
        motorName: "turn_head_motor",
        motorPathName: MotorPathName.TURN_HEAD,
        title: "Head Rotation",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.5884146341463414,
        touchPointCenterY: 0.6836206896551724,
    },
    {
        motorName: "thumb_right_stretch",
        motorPathName: MotorPathName.THUMB_RIGHT_STRETCH,
        title: "Thumb",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.6051829268292683,
        touchPointCenterY: 0.1413793103448276,
    },
    {
        motorName: "thumb_right_opposition",
        motorPathName: MotorPathName.THUMB_RIGHT_OPPOSITION,
        title: "Thumb Opposition",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.8048780487804879,
        touchPointCenterY: 0.3931034482758621,
    },
    {
        motorName: "index_right_stretch",
        motorPathName: MotorPathName.INDEX_RIGHT_STRETCH,
        title: "Index Finger",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.2423780487804878,
        touchPointCenterY: 0.3482758620689655,
    },
    {
        motorName: "middle_right_stretch",
        motorPathName: MotorPathName.MIDDLE_RIGHT_STRETCH,
        title: "Middle Finger",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.20198170731707318,
        touchPointCenterY: 0.531896551724138,
    },
    {
        motorName: "ring_right_stretch",
        motorPathName: MotorPathName.RING_RIGHT_STRECTH,
        title: "Ring Finger",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.2530487804878049,
        touchPointCenterY: 0.6629310344827586,
    },
    {
        motorName: "pinky_right_stretch",
        motorPathName: MotorPathName.PINKY_RIGHT_STRECTH,
        title: "Pinky",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.32698170731707316,
        touchPointCenterY: 0.7931034482758621,
    },
    {
        motorName: "thumb_left_stretch",
        motorPathName: MotorPathName.THUMB_LEFT_STRETCH,
        title: "Thumb",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.3978658536585366,
        touchPointCenterY: 0.13793103448275862,
    },
    {
        motorName: "thumb_left_opposition",
        motorPathName: MotorPathName.THUMB_LEFT_OPPOSITION,
        title: "Thumb Opposition",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.19588414634146342,
        touchPointCenterY: 0.3905172413793103,
    },
    {
        motorName: "index_left_stretch",
        motorPathName: MotorPathName.INDEX_LEFT_STRETCH,
        title: "Index Finger",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.756859756097561,
        touchPointCenterY: 0.3456896551724138,
    },
    {
        motorName: "middle_left_stretch",
        motorPathName: MotorPathName.MIDDLE_LEFT_STRETCH,
        title: "Middle Finger",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.8224085365853658,
        touchPointCenterY: 0.5293103448275862,
    },
    {
        motorName: "ring_left_stretch",
        motorPathName: MotorPathName.RING_LEFT_STRECTH,
        title: "Ring Finger",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.7842987804878049,
        touchPointCenterY: 0.6603448275862069,
    },
    {
        motorName: "pinky_left_stretch",
        motorPathName: MotorPathName.PINKY_LEFT_STRECTH,
        title: "Pinky",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.6875,
        touchPointCenterY: 0.7896551724137931,
    },
    {
        motorName: "shoulder_horizontal_left",
        motorPathName: MotorPathName.SHOULDER_HORIZONTAL_LEFT,
        title: "Shoulder Horizontal",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.12195121951219512,
        touchPointCenterY: 0.15948275862068967,
    },
    {
        motorName: "shoulder_vertical_left",
        motorPathName: MotorPathName.SHOULDER_VERTICAL_LEFT,
        title: "Shoulder Vertical",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.19207317073170732,
        touchPointCenterY: 0.20775862068965517,
    },
    {
        motorName: "upper_arm_left_rotation",
        motorPathName: MotorPathName.UPPER_ARM_LEFT_ROTATION,
        title: "Upper Arm Rotation",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.22560975609756098,
        touchPointCenterY: 0.4224137931034483,
    },
    {
        motorName: "elbow_left",
        motorPathName: MotorPathName.ELBOW_LEFT,
        title: "Elbow Position",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.19969512195121952,
        touchPointCenterY: 0.5551724137931034,
    },
    {
        motorName: "lower_arm_left_rotation",
        motorPathName: MotorPathName.LOWER_ARM_LEFT_ROTATION,
        title: "Lower Arm Rotation",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.3048780487804878,
        touchPointCenterY: 0.6387931034482759,
    },
    {
        motorName: "wrist_left",
        motorPathName: MotorPathName.WRIST_LEFT,
        title: "Wrist Position",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.3780487804878049,
        touchPointCenterY: 0.8181034482758621,
    },
    {
        motorName: "shoulder_horizontal_right",
        motorPathName: MotorPathName.SHOULDER_HORIZONTAL_RIGHT,
        title: "Shoulder Horizontal",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.8917682926829268,
        touchPointCenterY: 0.15948275862068967,
    },
    {
        motorName: "shoulder_vertical_right",
        motorPathName: MotorPathName.SHOULDER_VERTICAL_RIGHT,
        title: "Shoulder Vertical",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.8079268292682927,
        touchPointCenterY: 0.20775862068965517,
    },
    {
        motorName: "upper_arm_right_rotation",
        motorPathName: MotorPathName.UPPER_ARM_RIGHT_ROTATION,
        title: "Upper Arm Rotation",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.7515243902439024,
        touchPointCenterY: 0.4224137931034483,
    },
    {
        motorName: "elbow_right",
        motorPathName: MotorPathName.ELBOW_RIGHT,
        title: "Elbow Position",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.7530487804878049,
        touchPointCenterY: 0.5551724137931034,
    },
    {
        motorName: "lower_arm_right_rotation",
        motorPathName: MotorPathName.LOWER_ARM_RIGHT_ROTATION,
        title: "Lower Arm Rotation",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.676829268292683,
        touchPointCenterY: 0.6586206896551724,
    },
    {
        motorName: "wrist_right",
        motorPathName: MotorPathName.WRIST_RIGHT,
        title: "Wrist Position",
        sliderIconLeft: "/voice-assistant-svgs/personality/personality.svg",
        sliderIconRight: "/voice-assistant-svgs/personality/personality.svg",
        captionLeft: "closed",
        captionRight: "open",
        touchPointCenterX: 0.6577743902439024,
        touchPointCenterY: 0.8181034482758621,
    },
];

export const motorPathNameToConfig: Map<string, MotorConfiguration> = new Map();
for (const motor of motors) {
    motorPathNameToConfig.set(motor.motorPathName, motor);
}
