name: CIDocker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push
      uses: docker/bake-action@v6
      with:
        push: true
        set: |
          *.platform=linux/amd64      
          *.platform+=linux/arm64
          
