name: Docker Build Pipeline

on:
  push:
    branches: 
      - PR-900
  workflow_dispatch:

jobs:
  
  version-and-build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    name: Version Bump & Build Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: write 

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for tags

      # Bump version based on conventional commits messages
    - name: Automated version bump
      id: bump
      uses:  phips28/gh-action-bump-version@v11.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag-prefix: ''
        commit-message: "ci: bump version to {{version}} [skip ci]"

    # Set env variable for new version
    - name: Set VERSION env
      run: echo "VERSION=${{ steps.bump.outputs.newVersion }}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Github repository ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/bake-action@v6
      with:
        push: true
        set: |
          *.platform=linux/arm64
          *.tags=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          *.tags+=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ env.VERSION }}