name: Docker Build Pipeline

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build-and-version:
    # Skip this job if the commit message contains '[skip ci]'
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    name: Version Bump & Build Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for tags

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Github repository ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker
      uses: docker/bake-action@v6
      with:
        push: false
        set: |
          *.platform=linux/arm64
          *.cache-from=type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-cache:buildcache
          *.cache-to=type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-cache:buildcache,mode=max

    - name: Create tag based on conventional commits
      id: tag_version
      if: success()
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''
        release_branches: main
        default_bump: false

    - name: Build and push Docker with tags
      if: steps.tag_version.outputs.new_tag != ''
      uses: docker/bake-action@v6
      with:
        push: true
        set: |
          *.platform=linux/arm64
          *.cache-from=type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-cache:buildcache
          *.cache-to=type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-cache:buildcache,mode=max
          *.tags=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          *.tags+=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ steps.tag_version.outputs.new_tag }}