name: CI Pipeline

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  CI-Checks:
    # ignores [skip ci] commits
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    name: Cerebra CI-Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.22.3]
        
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies   
        run: npm ci
        
      - name: Run Lint   
        run: npx ng lint
        continue-on-error: true

      - name: Run Unit Tests
        if: ( success() || failure() ) && github.event_name == 'pull_request' 
        run: npx ng test --code-coverage --watch=false --browsers=NoSandbox

      - name: Upload test results
        uses: actions/upload-artifact@v7
        if: ( success() || failure() ) && github.event_name == 'pull_request'
        with:
          name: coverage-report
          path: coverage/cerebra/lcov.info

  SonarQube-Analysis:
    name: Analyze with SonarQube
    uses: ./.github/workflows/sonarqube.yml
    secrets: inherit
    needs: CI-Checks
    if: github.event_name == 'pull_request'
        
  CodeQL-Analysis:
    name: Analyze with CodeQl
    uses: ./.github/workflows/codeql.yml

  System-Tests:
    name: Run System Tests
    uses: ./.github/workflows/system-tests.yml
    secrets: inherit
    needs: CI-Checks
    if: github.event_name == 'pull_request' &&
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'develop'