name: SonarCloud-Analysis

on:
  workflow_call:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: coverage/cerebra/

      - name: SonarCloud-Scan
        uses: SonarSource/sonarqube-scan-action@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}